# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eRh7Q7ZfnuDmR3NHGfFy9HlU6eHIBxyp
"""

import streamlit as st
import torch
import torch.nn as nn
import torch.nn.functional as F
import open3d as o3d
import numpy as np
import tempfile
import os

# 1. Definisikan ulang resep AI-mu agar otak .pth bisa dibaca
class SimplePointNet(nn.Module):
    def __init__(self, num_classes):
        super(SimplePointNet, self).__init__()
        self.conv1 = nn.Conv1d(3, 64, 1)
        self.conv2 = nn.Conv1d(64, 128, 1)
        self.conv3 = nn.Conv1d(128, 1024, 1)
        self.fc1 = nn.Linear(1024, 512)
        self.fc2 = nn.Linear(512, 256)
        self.fc3 = nn.Linear(256, num_classes)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = self.conv3(x)
        x = torch.max(x, 2, keepdim=True)[0]
        x = x.view(-1, 1024)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

# 2. Desain Tampilan Web
st.title("🚀 Inspektur Wadah 3D AI")
st.write("Upload file .pcd kamu di sini untuk dianalisis otomatis!")

# Fitur Gembok Keamanan (Password)
password = st.sidebar.text_input("Masukkan Password", type="password")
if password != "wadahaman123":
    st.warning("Silakan masukkan password di menu sebelah kiri untuk mengakses AI.")
    st.stop()

# Tombol Upload
uploaded_file = st.file_uploader("Pilih file .pcd", type=['pcd'])

if uploaded_file is not None:
    # Simpan file sementara agar bisa dibaca Open3D
    with tempfile.NamedTemporaryFile(delete=False, suffix=".pcd") as tmp:
        tmp.write(uploaded_file.getvalue())
        tmp_path = tmp.name

    st.info("AI sedang memproses file 3D...")

    try:
        # Load Model pakai CPU
        device = torch.device("cpu")
        checkpoint = torch.load("best_model.pth", map_location=device)
        classes = checkpoint["classes"]
        model = SimplePointNet(len(classes)).to(device)
        model.load_state_dict(checkpoint["model_state"])
        model.eval()

        # Preprocessing Data Baru
        pcd = o3d.io.read_point_cloud(tmp_path)
        pcd_down = pcd.voxel_down_sample(voxel_size=0.05)
        points = np.asarray(pcd_down.points)

        # Samakan jumlah titik (1024)
        if points.shape[0] >= 1024:
            indices = np.random.choice(points.shape[0], 1024, replace=False)
        else:
            indices = np.random.choice(points.shape[0], 1024, replace=True)
        points = points[indices]

        # Normalisasi
        centroid = np.mean(points, axis=0)
        points = points - centroid
        m = np.max(np.sqrt(np.sum(points**2, axis=1)))
        if m > 0:
            points = points / m

        points_tensor = torch.tensor(points, dtype=torch.float32).transpose(0, 1).unsqueeze(0).to(device)

        # Proses AI Menebak
        with torch.no_grad():
            prediksi = model(points_tensor)
            persentase = F.softmax(prediksi, dim=1).squeeze() * 100

        st.subheader("Hasil Analisis:")
        skor_per_kelas = [(classes[i], persentase[i].item()) for i in range(len(classes))]
        skor_per_kelas.sort(key=lambda x: x[1], reverse=True)

        top_1_kelas = skor_per_kelas[0][0]

        # Logika Trik Cacat Ganda & Threshold 15%
        if top_1_kelas.lower() == "valid":
            st.success(f"✅ Barang ini Valid Sempurna! (Keyakinan: {skor_per_kelas[0][1]:.2f}%)")
        else:
            st.error("⚠️ Peringatan: Barang terdeteksi CACAT dengan alasan berikut:")
            for nama_kelas, skor in skor_per_kelas:
                if nama_kelas.lower() != "valid" and skor >= 15.0:
                    st.write(f"- **{nama_kelas}** (Confidence: {skor:.2f}%)")

    except Exception as e:
        st.error(f"Terjadi kesalahan saat memproses: {e}")
    finally:
        os.remove(tmp_path) # Hapus file sementara agar server tidak penuh